dataset: cifar10
dataroot: "./data/raw"
forget_fraction: 0.2
seed: 42
split_dir: "/content/gdrive/My Drive/mia_splits"
batch_size: 128
num_workers: 2
pin_memory: true
model_path: "/content/gdrive/My Drive/mia_checkpoints/pretrained_cifar10.pt"
check_path: "/content/gdrive/My Drive/mia_checkpoints/finetune_unlearned_model.pt"
results_path: "/content/gdrive/My Drive/mia_checkpoints/finetune_results.txt"
learning_rate: 0.00005
unlearn_epochs: 5
print_freq: 0
with_l1: true
alpha: 0.00005
no_l1_epochs: 2
eval_every: 1
print_accuracies: true
