dataset: cifar10
dataroot: "./data/raw"
forget_fraction: 0.1
seed: 42
batch_size: 256
num_workers: 2
pin_memory: true
model_path: "./models/pretrained_cifar10.pt"
check_path: "./results/ssd_unlearned_model.pt"
learning_rate: 0.0001
dampening_constant: 0.1
selection_weighting: 0.1
eval_every: 1
print_accuracies: true
device: null
